version: "3.9"

services:
  zookeeper:
    extends:
      file: docker-compose.yaml
      service: zookeeper

  kafka:
    extends:
      file: docker-compose.yaml
      service: kafka

  init-kafka:
    extends:
      file: docker-compose.yaml
      service: init-kafka

  greenplum:
    extends:
      file: docker-compose.yaml
      service: greenplum

  minio:
    extends:
      file: docker-compose.yaml
      service: minio

  redis:
    extends:
      file: docker-compose.yaml
      service: redis

  create_minio_buckets:
    extends:
      file: docker-compose.yaml
      service: create_minio_buckets

  prometheus:
    extends:
      file: docker-compose.yaml
      service: prometheus

  grafana:
    extends:
      file: docker-compose.yaml
      service: grafana

  taskmanager:
    extends:
      file: docker-compose.yaml
      service: taskmanager
    volumes:
      - ${PWD}/services/pyflink:/work_dir/service
      - ${PWD}/utils:/work_dir/utils

  pyflink:
    extends:
      file: docker-compose.yaml
      service: pyflink
    volumes:
      - ${PWD}/services/pyflink:/work_dir/service
      - ${PWD}/utils:/work_dir/utils

  orchestrator:
    extends:
      file: docker-compose.yaml
      service: orchestrator
    volumes:
      - ${PWD}/services/orchestrator:/work_dir/service
      - ${PWD}/utils:/work_dir/utils

  data_generator:
    extends:
      file: docker-compose.yaml
      service: data_generator
    volumes:
      - ${PWD}/services/data_generator:/work_dir/service
      - ${PWD}/utils:/work_dir/utils

  result_viewer:
    extends:
      file: docker-compose.yaml
      service: result_viewer
    volumes:
      - ${PWD}/services/result_viewer:/work_dir/service
      - ${PWD}/utils:/work_dir/utils

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  greenplum_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  shared_data:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: ${PWD}/services/shared_data

networks:
  node-network:
    driver: bridge